replicaCount: 2

image:
  repository: 764520352358.dkr.ecr.eu-north-1.amazonaws.com/lesson-5-ecr
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:              # <— ці змінні підуть у ConfigMap
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECRET_KEY: "change-me"
  DJANGO_DB_NAME: "mydb"
  DJANGO_DB_USER: "myuser"
  DJANGO_DB_PASSWORD: "mypassword"
  DJANGO_DB_HOST: "mydb.example"
  DJANGO_DB_PORT: "5432"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: false
  className: nginx
  host: yourdomain.com
  path: /
  pathType: Prefix
  tls: false